server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackuri: forword:/userServiceFallBack
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
          filters:
            - name: CircuitBreaker
              args:
                name: DEPARTMENT-SERVICE
                fallbackuri: forword:/departmentServiceFallBack


#hystrix:
#  command:
#    fallbackcmd:
#       execution:
#         isolation:
#            thread:
#              timeoutInMilliseconds: 4000

#mnagement:
#   endpoints:
#     web: 
#       exposure:
#          include: hystricx.stream


#ADDED TO BOOTSTRAP FILE
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.1.188:8761/eureka/
  instance:
    #hostname: localhost
    prefer-ip-address: true